[package]
name = "embedded-example"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f4xx-hal = { version = "0.14", features = ["stm32f411"] }

[[bin]]
name = "embedded-example"
test = false
bench = false
